### PR TITLE
Use cluster cache for group queries.

### PR DESCRIPTION
**Pull request by xaviershay**
Had a spare half hour today :) Please read carefully, it's been a while since I touched this code.

Using our production dataset, before:

```
INFO  [2016-01-26 23:29:01.275] QUERY [::1]:63221 4.052 "?somehost"
```

After:
```
INFO  [2016-01-26 23:27:25.457] QUERY [::1]:62195 0.001 "?somehost"
```

@jeeyoungk @drcapulet

### CODE REVIEW

**Comment by xaviershay** [comment]
Build failure is the known range spec that we don't support yet.

**Comment by drcapulet** [comment]
LGTM, probably want to re-run after merging the cluster spec first though.

**Comment by grierj** [comment]
somewhat concerning that the travis CI tests failed, but they pass locally.  I'll try to spin up a linux VM in a few to make sure it's not a Mac v. Linux issue.

**Comment by grierj** [comment]
Oi, just saw the comment about known build failure.  LGTM then.

**Pull request merged**
